### ISSUE TITLE
Need Visual Basic solution.

### ISSUE THREAD

**Issue by ZiCog** [ZiCog/fibo_4784969#3]
I will be quite happy if the Fibonacci code written in open-source Visual Basic could be included in the repository.

**Comment by ejolson2005** [comment]
The Visual Basic code is in a post on the Raspberry Pi Forum at

https://www.raspberrypi.org/forums/viewtopic.php?p=1418137#p1418137

Please let me know if you have trouble with the above link and getting the code.

All the best,
Eric

**Comment by ZiCog** [comment]
VisualBasic solution checked in. Please look it over.

Also Maxima and Julia solutions.

Thanks.
